language: node_js

#addons:
#  - artifacts: true

before_install:
  - cd PhantomCSS

before_script:
  - "gem install travis-artifacts"
  - cd AdminLTE-master/
  - python -m SimpleHTTPServer 8080 &
  - sleep 3
  - cd ..
  - npm install -g casperjs

node_js:
  - "node"

script: casperjs test AdminLTE-Test/testsuite.js

after_script:
  - "travis-artifacts upload --path screenshots/*"
