language: node_js

addons:
  - artifacts: true

before_install:
  - cd PhantomCSS

before_script:
  - "gem install travis-artifacts"
  - cd AdminLTE-master/
  - python -m SimpleHTTPServer 8080 &
  - sleep 3
  - cd ..
  - npm install -g casperjs
  - pip install selenium
  - pip install needle

node_js:
  - "node"

script: 
  - casperjs test AdminLTE-Test/testsuite.js
  - nosetests ../Needle/test_AdminLTE.py

after_script:
  - "travis-artifacts upload --path screenshots/*"
